db:
 host: "64.227.37.97"
 port: "3306"
 user: "njclabs"
 database: "nrs"


 
tls.keystore:
 type: "pkcs12"
 alias: "server"
 path: "certs/apix-generic-db-sapi.p12"


 
json.logger: 
 application:
  environment: "dev"